name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies for all workspaces
      - name: Install Dependencies
        run: npm install

      # Build all workspaces
      - name: Build All Workspaces
        run: npm run build:all

      # Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload the React app's dist folder (including the Lit bundle)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/docs/dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4